import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { GiCat } from "react-icons/gi"; // Logo
import {
  BsFillHeartFill,
  BsFillChatRightFill,
  BsFillHouseFill,
} from "react-icons/bs"; // Heart, Chat and House Icons
import { fetchCats } from "./api/cats";
import Swal from "sweetalert2";

export default function Home() {
  // useState
  const [images, setImages] = useState([]);
  const [selectedItem, setSelectedItem] = useState([]);
  const [showChat, setShowChat] = useState(false);
  // Fetching data
  const getCats = async () => {
    const arrayOfNewCats = await fetchCats();
    let allCats = images;

    arrayOfNewCats.forEach((e) => {
      allCats.push(e);
    });

    setImages([...allCats]);
  };
  // Getting Cats Images
  useEffect(() => {
    let isCancelled = false;
    // Calling function
    if (!isCancelled) {
      getCats();
    }
    // Cleanup
    return () => {
      isCancelled = true;
    };
  }, []);
  // Handling selected image
  const handleItemClick = (index) => {
    let array = selectedItem;

    if (!selectedItem.includes(index)) {
      array.push(index);
      setSelectedItem([...array]);
    } else {
      array.pop(index, 1);
      setSelectedItem([...array]);
    }
  };
  // Opening chat and closing
  const handleChat = () => {
    Swal.fire({
      icon: "error",
      title: "Oops...",
      text: "Comments aren't available for now! Sorry for the inconvenience.",
    });
  };

  return (
    <>
      <Head>
        <title>Kittygram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" grid place-content-center">
          <div className=" relative mt-36 w-[20rem] h-[38rem] rounded-[1.8rem] bg-primary">
            {/* Logo */}
            <Link href="/">
              <GiCat size="5rem" className=" text-secondary m-auto mt-6" />
            </Link>
            {/* Footer */}
            <div className=" absolute inset-x-0 bottom-0 w-[20rem] h-[5.75rem] rounded-b-[1.8rem] bg-secondary">
              <BsFillHouseFill
                size="3rem"
                className=" text-primary m-auto mt-5 cursor-pointer"
              />
            </div>
            {/* Posts Div*/}
            <div className=" w-[20rem] h-[25.8rem] overflow-auto scrollbar-hide">
              {/*Returning posts of cats*/}
              {images.map((image, index) => {
                return (
                  <div
                    key={index}
                    className=" relative mt-8 mb-6 m-auto w-[16rem] h-[22rem] rounded-b-lg rounded-t-[0.7rem] bg-secondary"
                  >
                    {/* Heart Icon */}
                    <BsFillHeartFill
                      size="3.5rem"
                      className={
                        selectedItem.includes(index)
                          ? " absolute bottom-0 m-4 text-red-600 drop-shadow-md cursor-pointer transition duration-500 ease-in-out"
                          : " absolute bottom-0 m-4 text-primary drop-shadow-md cursor-pointer transition duration-500 ease-in-out"
                      }
                      onClick={() => handleItemClick(index)}
                    />
                    {/* Chat Icon */}
                    <BsFillChatRightFill
                      size="2.5rem"
                      className=" absolute right-0 bottom-0 m-6 text-primary drop-shadow-md cursor-pointer"
                      onClick={() => handleChat()}
                    />
                    {/* Image */}
                    <img
                      src={image.url}
                      className=" w-[16rem] h-[19rem] rounded-t-lg bg-slate-300"
                    ></img>
                  </div>
                );
              })}
              {/*Returning posts of cats End*/}
              {/* Show more cats */}
              <h1
                onClick={() => getCats()}
                className=" text-center cursor-pointer text-secondary mb-4"
              >
                See more
              </h1>
              {/* Show more cats End*/}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
